#!/bin/bash
mkdir -p lib
if [ ! -d BQN ]; then
  echo "Clone or symlink dzaima/BQN in base directory!"; exit
fi
./getBQN.sh
if [ ! -f lib/json-20210307.jar ]; then
  echo "downloading json-20210307.jar"
  curl -L 'https://search.maven.org/remotecontent?filepath=org/json/json/20210307/json-20210307.jar' > lib/json-20210307.jar
fi
if [ ! -f lib/jsoup-1.13.1.jar ]; then
  echo "downloading jsoup-1.13.1.jar"
  curl 'https://jsoup.org/packages/jsoup-1.13.1.jar' > lib/jsoup-1.13.1.jar
fi

rm -f bqnbot.jar
rm -rf classes
mkdir -p classes
javac -cp 'lib/*' -Xmaxerrs 1000 -d classes $(find src -name '*.java')
cd classes
jar cvfe bqnbot.jar dzaima.Main * > /dev/null
mv bqnbot.jar ../bqnbot.jar
cd ..
rm -r classes